### ISSUE TITLE
Doesn't load VGA font

### ISSUE THREAD

**Issue by rumbledethumps** [a740g/VGA-Font-Editor#1]
Files that are exactly 2048, 3584, and 4096 bytes are obviously 8, 14, and 16 row VGA fonts, but all I get is a "Failed to load" error.

**Comment by a740g** [comment]
Are these PSFs or raw VGA fonts?

If these are raw VGA fonts, then use the included `bin2psf.bas` to convert the file to PSF first and then load the PSF file in the editor.

I am planning to integrate the import of raw VGA fonts directly into the main editor in the next update,

**Comment by rumbledethumps** [comment]
I'm working on hardware emulation and don't remember much about bitmap file formats. Everything I come across is just the data as it exists in ROM.

**Comment by a740g** [comment]
Added support for importing raw font dumps.

**Comment by rumbledethumps** [comment]
Works great. Thanks.
